#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_FILE="$ROOT_DIR/architektur.md"
TIMESTAMP="$(date '+%Y-%m-%d %H:%M:%S %Z (%z)')"

collect_paths() {
  (
    cd "$ROOT_DIR"

    # Top-level snapshot (exclude transient env/cache dirs).
    find . -mindepth 1 -maxdepth 1 \
      ! -name ".venv" \
      ! -name ".venv-wheelhouse" \
      ! -name ".pytest_cache" \
      -printf '%P\t%y\n'

    # Detailed subtrees with practical depth limits.
    find configs -maxdepth 2 -name '__pycache__' -prune -o -printf '%p\t%y\n'
    find simple_sim -maxdepth 3 -name '__pycache__' -prune -o -printf '%p\t%y\n'
    find scripts -maxdepth 1 -name '__pycache__' -prune -o -printf '%p\t%y\n'
    find tools -maxdepth 2 -name '__pycache__' -prune -o -printf '%p\t%y\n'
    find gui -maxdepth 3 -name '__pycache__' -prune -o -printf '%p\t%y\n'
    find tests -maxdepth 1 -name '__pycache__' -prune -o -printf '%p\t%y\n'
    find docs -maxdepth 3 -name '__pycache__' -prune -o -printf '%p\t%y\n'
    # Keep images concise: include top-level assets and sample profile folders only.
    find images -maxdepth 1 -name '__pycache__' -prune -o -printf '%p\t%y\n'
    find images/samples -maxdepth 2 -type d -name '__pycache__' -prune -o -type d -printf '%p\t%y\n' 2>/dev/null || true
    find third_party -maxdepth 2 -name '__pycache__' -prune -o -printf '%p\t%y\n'
    # Keep outputs concise: directories only (no generated runtime file lists).
    find outputs -maxdepth 2 -type d -name '__pycache__' -prune -o -type d -printf '%p\t%y\n' 2>/dev/null || true
  ) | sed 's#^\./##' | sort -u
}

render_structure() {
  collect_paths | awk -F '\t' '
    {
      path = $1
      typ = $2
      n = split(path, parts, "/")
      depth = n - 1
      indent = ""
      for (i = 0; i < depth; i++) {
        indent = indent "  "
      }
      label = parts[n]
      if (typ == "d") {
        label = label "/"
      }
      print indent "- " label
    }
  '
}

{
  echo "# Architecture"
  echo
  echo "Last update: $TIMESTAMP"
  echo
  echo "This file is auto-generated by \`tools/update_architektur_md.sh\`."
  echo
  echo "## How To Read"
  echo
  echo "- Purpose: complete architecture and project structure snapshot."
  echo "- Focus: source/config/scripts/docs/GUI + concise runtime folder layout."
  echo "- Excluded noise: \`__pycache__/\`, \`.venv/\`, \`.venv-wheelhouse/\`, \`.pytest_cache/\`."
  echo "- Update command: \`./tools/update_architektur_md.sh\` (from \`Simple-Sim/\`)."
  echo
  echo "## Architecture Conventions"
  echo
  echo "- New CLI workflows: add entrypoints in \`scripts/\`; keep reusable logic in \`simple_sim/\`."
  echo "- New validation/migration helpers: place in \`tools/\`."
  echo "- New GUI features: use \`gui/tabs/<feature>/\` with \`tab.py\`, \`logic.py\`, and \`ui.py\` when applicable."
  echo "- Shared GUI primitives: place reusable widgets in \`gui/components/\` and cross-tab helpers in \`gui/utils/\`."
  echo "- New docs: add user-facing guides to \`docs/guides/\`, engineering notes to \`docs/technical/\`, and experiment logs to \`docs/training_logs/\`."
  echo "- Runtime outputs: write generated artifacts under \`outputs/\`; keep source folders free of run artifacts."
  echo
  echo "## Project Structure (Auto)"
  echo
  echo '```text'
  echo "Simple-Sim/"
  render_structure
  echo '```'
  echo
  echo "Generated with: \`tools/update_architektur_md.sh\`"
} > "$OUT_FILE"

echo "Updated: $OUT_FILE"
