"""Persisted Tk variable mapping for pipeline tab settings."""

from __future__ import annotations

PERSISTED_FIELD_MAP: tuple[tuple[str, str], ...] = (
    ("pipeline.run_mode", "var_run_mode"),
    ("pipeline.run_count", "var_run_count"),
    ("pipeline.dataset_mode", "var_dataset_mode"),
    ("pipeline.config", "var_config"),
    ("pipeline.out", "var_out"),
    ("pipeline.model", "var_model"),
    ("pipeline.autosnap", "var_autosnap"),
    ("pipeline.snap_every", "var_snap_every"),
    ("pipeline.snap_keep", "var_snap_keep"),
    ("pipeline.continue_epochs", "var_continue_epochs"),
    ("pipeline.continue_out_mode", "var_continue_out_mode"),
    ("pipeline.name", "var_name"),
    ("pipeline.name_ts", "var_name_ts"),
    ("pipeline.dataset_selection", "var_dataset"),
    ("pipeline.dataset_multi_enabled", "var_dataset_multi"),
    ("pipeline.dataset_multi_paths", "var_dataset_multi_paths"),
    ("pipeline.profile_model", "var_profile_model"),
    ("pipeline.profile_model_locked", "var_profile_model_lock"),
    ("pipeline.profile_build_preset", "var_profile_build_preset"),
    ("pipeline.render_backend", "var_render_backend"),
    ("pipeline.filter.cardinal_rotation_90", "var_filter_cardinal_rotation_90"),
    ("pipeline.filter.enable_rotation", "var_filter_enable_rotation"),
    ("pipeline.filter.enable_blur", "var_filter_enable_blur"),
    ("pipeline.filter.enable_grain", "var_filter_enable_grain"),
    ("pipeline.filter.enable_brightness", "var_filter_enable_brightness"),
    ("pipeline.filter.enable_contrast", "var_filter_enable_contrast"),
    ("pipeline.filter.rotation_strength", "var_filter_rotation_strength"),
    ("pipeline.filter.blur_strength", "var_filter_blur_strength"),
    ("pipeline.filter.grain_strength", "var_filter_grain_strength"),
    ("pipeline.filter.brightness_strength", "var_filter_brightness_strength"),
    ("pipeline.filter.contrast_strength", "var_filter_contrast_strength"),
    ("pipeline.filter.enable_perspective", "var_filter_enable_perspective"),
    ("pipeline.filter.perspective_strength", "var_filter_perspective_strength"),
    ("pipeline.filter.enable_motion_blur", "var_filter_enable_motion_blur"),
    ("pipeline.filter.motion_blur_strength", "var_filter_motion_blur_strength"),
    ("pipeline.filter.enable_saturation", "var_filter_enable_saturation"),
    ("pipeline.filter.saturation_factor", "var_filter_saturation_factor"),
    ("pipeline.filter.enable_hue_shift", "var_filter_enable_hue_shift"),
    ("pipeline.filter.hue_shift_deg", "var_filter_hue_shift_deg"),
    ("pipeline.filter.enable_shadow", "var_filter_enable_shadow"),
    ("pipeline.filter.shadow_strength", "var_filter_shadow_strength"),
    ("pipeline.filter.enable_reflection", "var_filter_enable_reflection"),
    ("pipeline.filter.reflection_strength", "var_filter_reflection_strength"),
    ("pipeline.filter.enable_vignetting", "var_filter_enable_vignetting"),
    ("pipeline.filter.vignetting_strength", "var_filter_vignetting_strength"),
    ("pipeline.filter.enable_chromatic_aberration", "var_filter_enable_chromatic_aberration"),
    ("pipeline.filter.chromatic_strength", "var_filter_chromatic_strength"),
    ("pipeline.filter.enable_jpeg_compression", "var_filter_enable_jpeg_compression"),
    ("pipeline.filter.jpeg_quality", "var_filter_jpeg_quality"),
    ("pipeline.filter.enable_color_temperature", "var_filter_enable_color_temperature"),
    ("pipeline.filter.color_temperature_kelvin", "var_filter_color_temperature_kelvin"),
    ("pipeline.filter.enable_lens_distortion", "var_filter_enable_lens_distortion"),
    ("pipeline.filter.distortion_k1", "var_filter_distortion_k1"),
    ("pipeline.filter.enable_dust", "var_filter_enable_dust"),
    ("pipeline.filter.dust_density", "var_filter_dust_density"),
    ("pipeline.filter.enable_sharpen", "var_filter_enable_sharpen"),
    ("pipeline.filter.sharpen_strength", "var_filter_sharpen_strength"),
)
